### ISSUE TITLE
A few items dont work

### ISSUE THREAD

**Issue by DOSorDIE4CsP** [JensForstmann/Factorio-Blueprint-To-Combinator#1]
The website make in general what it should
But some item are missing in the combinators
Here are the item list:
    32x curved-rail
    305x straight-rail
    10x rail-chain-signal
    13x rail-signal
    5x big-electric-pole
    3x roboport
    6x train-stop
    356x fast-inserter
    5x logistic-chest-requester
    116x medium-electric-pole
    76x filter-inserter
    73x steel-chest
    1x logistic-chest-storage
    1074x fast-transport-belt
    5x arithmetic-combinator
    33x fast-splitter
    4x logistic-chest-passive-provider
    3x constant-combinator
    43x small-lamp
    106x fast-underground-belt
    12x cargo-wagon
    10x locomotive
    100x coal
    136x electric-furnace
    439x speed-module
    166x long-handed-inserter
    55x assembling-machine-3
    98x speed-module-2
    14x chemical-plant
    60x pipe-to-ground
    195x pipe
    5x oil-refinery
    8x storage-tank
    16x pump
    8x fluid-wagon

and that is missing in the blueprint (curved-rail definitiv doesnt exist anymore)

305x straight-rail
10x rail-chain-signal
13x rail-signal
5x big-electric-pole
3x roboport
6x train-stop
356x fast-inserter
116x medium-electric-pole
76x filter-inserter
73x steel-chest

I hope you can fix that.
Thank you for you awsome website!

**Comment by JensForstmann** [comment]
Hi @DOSorDIE4CsP 

I've just pushed a fixed (and also added support for blueprint books).

Now it translates `straight-rail` into 1 `rail` and `curved-rail` into 4 `rail`.

Can you confirm, that it's working now? If not please supply me with a test bp string so I can reproduce it.

**Comment by DOSorDIE4CsP** [comment]
Hi! 

I test it and it works now! 
Thank you so much, it make my life on the Factorio Server much easier.

⁣Gesendet mit BlueMail ​

**Comment by JensForstmann** [comment]
Nice to see that it's useful to others as well 👌
