### ISSUE TITLE
Items missing?

### ISSUE THREAD

**Issue by lordfiSh** [JensForstmann/Factorio-Blueprint-To-Combinator#2]
![image](https://user-images.githubusercontent.com/389680/78421417-c0607280-7657-11ea-8fab-f443a2b5fc48.png)

Import Blueprint: 
`0eNqtW+1O4zAQfJf8TpA/k9JXOaGTaU2xSNMocRE91Hc/94MrOlxoZvcH0EJ33PV4bLM7fS8e263vh9DFYv5ehMWmG4v5r/diDKvOtYffxV3vi3kRol8XZdG59eHZ6Kths3jxsWpdtwzdqurdstiXReiW/q2Yy/1DWfguhhj8CfD4ZPe7264f/ZBecIHaPo7RxbDpEny/GcPxYRo4wVTizpbFLj2Q9s7u9+UXHHXBWbu2TW9n3WdwmjOKyGHomzC+hTA/zMwXNHFGy4HZf2AvQ+WWr65b+GW1TTM7rIZN+lk9+jZmspQnVJl4WIbBL05/q8sPDjfb2G9jkRmyRoesvx8xdFcGbLIDthuXRswMY9HEZpPGsWA29+D01WhaB6ahEX9aIldTlJK4KhWQpaItSzU9S42sSyQ1AyxMIB9LWplIYjVtZQI5NlPOgCa348rZhCMgj3DZAsbofVstw9i3blcd8a6unFnK9tUN4XT+HU7F6Fbj4TUf8elb9NWYjuj0Y+369DW8HEZ8cu3oy/zrfjiLsjGfz/nsSXvZcqJ/i+fY42wdM87kqHM51jlsORlb5rCNzoGryeAqB66bHLieCp5/4zKHbaZii+yisjlsOxU7S6ZROex6KnZ+vrPvu5mKbW6f79lNl9KPO+npSpruuTG050vu/+todrrlHQY/Aw/+KXRpP0wX7cXgoz9uaFfCGiysxsIsFmawMI2FKSxMQmECisLGwhLDZhGjbOr6OP+/dI+FzbCwBgursTBwSgwWprEwhYVJKExAUdhYWGLYLGKUYetj6mKsMaHVmNBqTGj1VaE9uz9uuERXQ1g9x+8wLAOGYcDQDBiKAUPSMQQdguFdMEwGAycGWtkWipoqdYtJ3WJSt1elfvucWgbdWwbdWwbdWwbdWwbdWwbdW7ruLV33lq57S9e9vab7qRAWEtjUTcBgm4DBNgHDsAkYhk3AMAjYMAjYMAjYMAjY0AVs6AI2dAEbuoANXcAGErCBBKwxAWtMwJpBwJpBwJrOs6bzrCGeNcSzwnhWGM+KgWfFwLOi86zoPCuIZwXxLDGeJcazZOBZMvAs6TxLOs8S4lkiPAuIZgGxLOgkCzrHgkyxIDMsEIIFwi8mY0zFDCJm0DBdwnQFQwKG9Isdx9hpzHAYM5zF9KOYfhJDBzF0DmPXauxWzXCpZrhT06/U9Bs1dKGG7tNY3QMrezBUPRiKHoZe+GQomzBUTRiKJgw1E3rJhF4xoRdM6PUSerkEqpZAxRKs44E1PBj6HQztDoZuB0Ozg6HXwdDqYOh00Bsd9D4Hvc1B73LQmxxQjwNqcWCOBszQgPkZGOwMDG4GBjMDg5eBwcrA4GSgGxlqxItUI1YkulcBsipATgXIqIB5/zDrH+b8w4x/mO8Ps/1hrj/M9Id5/iDLH+T4gwx/kN8PsvtBbj/I7IcZyjE/OWYnx9zkmJkc85JjVnLMSQ4ZySEfOWQjh1zkkIn8Bg/5Q3n68NH802eSy+LVD+MRpmm0FFZZY8R+/xdo3zWm`

refined-hazard-concrete-right seems to be missing

**Comment by JensForstmann** [comment]
Thanks for opening an issue. I'll look into this.

**Comment by JensForstmann** [comment]
@lordfiSh I've added support for hazard-conrete-left & -right. Your example bp will output a combinator with these signals:

- 2x substation
- 4x small-lamp
- 1x se-rocket-landing-pad
- 8x kr-advanced-underground-belt
- 4x kr-advanced-loader
- 1x steel-display-small
- 8x textplate-small-steel
- 118x refined-concrete
- 93x refined-hazard-concrete
