### ISSUE TITLE
Combinator Signals Exceed Chest Size

### ISSUE THREAD

**Issue by nukedpenguin** [JensForstmann/Factorio-Blueprint-To-Combinator#8]
I propose that you add a way to divide the signal in half (rounding up to the nearest whole) and link to multiple requester chests as needed if one requester chest would be filled up by the request, this would make the tool a bit more useful, but it's still extremely useful as is. 
For example, I have a blueprint that uses 482 beacons, and I used your tool and that signal requests for 482 beacons in 1 chest, but the chest only holds 480 beacons, if the combinator instead gave a signal for 241 beacons linked to 2 requester chests, or even have additional combinator requester chest sets for same item types that exceed more than 1 chest (like 480 beacon combinator then a 2 beacon combinator linked to their own requester chests). My blueprint is not that large, but I could see this being a bigger issue for someone who is using thousands of beacons.

**Comment by JensForstmann** [comment]
You can do that directly ingame with an arithmetic combinator.
